### ISSUE TITLE
Getting error when try to deploy subgraph in graph node

### ISSUE THREAD

**Issue by a8uhnf** [balancer-labs/balancer-subgraph#49]
Getting error in graph node logs when try to deploy balancer subgraph 

```
Aug 21 13:15:36.545 ERRO Subgraph instance failed to run: RPC error: Error { code: MethodNotFound, message: "the method trace_filter does not exist/is not available", data: None }, code: SubgraphSyncingFailure, id: QmTMsUH9rUVjpBTDRNuUcNHM3rT9ZZmxkDmTYmyKUpzEJn, subgraph_id: QmTMsUH9rUVjpBTDRNuUcNHM3rT9ZZmxkDmTYmyKUpzEJn, component: SubgraphInstanceManager
Aug 21 13:15:41.071 INFO Syncing 1 blocks from Ethereum., code: BlockIngestionStatus, blocks_needed: 1, blocks_behind: 1, latest_block_head: 10703787, current_block_head: 10703786, network_name: mainnet,
component: BlockIngestor
```
To run graph-node, I use my geth-node address as `--ethereum-rpc` flag. Do I need to enable any `rpcapi` during running geth node?

**Comment by mikemcdonald** [comment]
Are you running an archive node? There are calls that require historical data. Also not sure if geth has tracing as a feature

**Comment by a8uhnf** [comment]
@mikemcdonald thanks for the reply. Discovered that geth doesn't have tracing feature. setup a parity node for graph-node
